### ISSUE TITLE
[REQ] Patch local images

### ISSUE THREAD

**Issue by duffney** [project-copacetic/copacetic#230] opened 2023-07-31 21:49 UTC
### What kind of request is this?

Improvement of existing experience

### What is your request or suggestion?

Is it possible \ desirable to allow Copa to patch local images instead of requiring a remote registry? At the moment when Copa is used as part of a build pipeline you have to push your image to a remote registry, patch it, then push the image to the registry again. With the ability to patch local images you could build, patch, and then only push the image once.

**Comment by sozercan** [comment] 2023-08-01 22:26
@duffney thanks for the issue! Looks like duplicate of #177, closing this one. feel free to re-open if it's not duplicate.

**Closed** 2023-08-01 22:26 UTC
Labels: enhancement

**Comment by duffney** [comment] 2023-08-08 14:05
#117 is the exact same, sorry about that. I should have looked closer at the issues. Thanks for the comment @sozercan. :)
