### ISSUE TITLE
[REQ] Add Oracle Linux as supported OS

### ISSUE THREAD

**Issue by slowjoe007** [project-copacetic/copacetic#190] opened 2023-06-17 14:36 UTC
### What kind of request is this?

New feature

### What is your request or suggestion?

Currently, Oracle Linux (https://hub.docker.com/_/oraclelinux) cannot be patched and the following error message is shown:
```text
Error: unsupported osType oracle specified
```
Please, add support for Oracle Linux.

Note: Oracle Linux 7 uses `yum`, while starting with version 8 `dnf` is used as package manager.

**Comment by sozercan** [comment] 2023-07-21 18:41
looks like there are `fips` packages in non-fips images that are causing issues. This will need further investigation.

`	* downloaded package libgcrypt version 1.8.5-7.el8_6 lower than required 10:1.8.5-7.el8_6_fips for update`
https://github.com/project-copacetic/copacetic/actions/runs/5625368437/job/15244418767?pr=207#step:6:2476

**Comment by MiahaCybersec** [comment] 2024-05-10 17:40
Oracle was attempted to be added in PR #207 but the PR had to be closed due to an update error. For some reason, Copa will throw an error similar to the one below despite no fips packages being present in the non-fips version of Oracle.

`        * downloaded package libgcrypt version 1.8.5-7.el8_6 lower than required 10:1.8.5-7.el8_6_fips for update
`

Note that this error appears to only be present on Oracle version 8.8

### Reproducing The Bug

`docker pull aquasec/trivy`
`docker pull oraclelinux:8.8`

Download the Copa codebase from [my fork](https://github.com/MiahaCybersec/copacetic/tree/oracle) and run `make` in the root of the project. In the commands below, all files and directories were kept in my home folder.

`unzip copacetic-oracle.zip`
`cd copacetic-oracle`
`make`
`cd /dist/linux_amd64/release`

Run the Trivy scan and save output in the release folder. This is just for testing to simplify commands.

`docker run aquasec/trivy -f json image oraclelinux:8.8 > ./oracle8.8-scan.json`

Attempt to patch the image with the `json` Trivy just gave us.

`./copa patch -r ./oracle8.8-scan.json -i [docker.io/library/oraclelinux:8.8](http://docker.io/library/oraclelinux:8.8)`

We should get the error shown at the top of this comment. What makes this bug rather odd is that the package throwing the error is a non-fips package. To verify this we run the following commands.

`docker run -it oraclelinux:8.8`
`yum deplist libgcrypt`

There is a dependency on `fipscheck`, but this does not inherently mean that the package is compiled with fips support. From what I've been able to tell thus far, that dependency is for when fips support is enabled for Oracle.

If we attempt to update the package within the container with the following commands, we see no errors and `libgcrypt` is not listed as a package.

`docker run -it oraclelinux:8.8`
`yum update`

### Next Steps

A good next step here would be to diagnose the source of the bug with [delve](https://github.com/go-delve/delve).

**Comment by MiahaCybersec** [comment] 2024-05-13 22:02
Due to the non-standard way that Oracle handles this, I propose the Copa team to take one of three implementations.

- Add a patch to Trivy upstream to resolve this issue
- Decide Oracle isn't first class support, add that to docs and close the issue
- Add a patch to Copa to handle this edge case scenario 

I believe options one and two to be the best approaches, but Copa could modify the way packages are patched if the team believes that is the best route to take. Any input on this @ashnamehrotra @sozercan?

**Comment by ashnamehrotra** [comment] 2024-05-16 17:05
Thank you for investigating this @MiahaCybersec! I agree, I don't think we should hard code this edge case scenario in Copa. Depending on the priority of this issue, it could be worth adding a patch to Trivy upstream, @sozercan may have a better idea.

**Comment by sozercan** [comment] 2024-05-16 17:18
@ashnamehrotra will this work with the new update all functionality? is blocker only on the scanner front?

**Comment by ashnamehrotra** [comment] 2024-05-20 15:12
@sozercan yes that is correct, with update all we wouldn't get this issue.

**Closed** 2024-07-29 23:27 UTC
Labels: enhancement, LFX mentorship - do not work on
