### ISSUE TITLE
[BUG] Copa hangs when patching nginx:1.21.6

### ISSUE THREAD

**Issue by ashnamehrotra** [project-copacetic/copacetic#504] opened 2024-02-14 17:29 UTC
### Actual Behavior

Log output during patching, gets stuck at diff phase:

```

...
 => apt update                                                                                                                                                                                           2.3s 
 => sh -c apt install --no-install-recommends --allow-change-held-packages -y libxml2 tar libcurl4 libsystemd0 libc-bin libgnutls30 libtirpc3 libudev1 libx11-data libxslt1.1 perl-base libfreetype6 li  8.8s 
 => sh -c grep "^Package:\|^Version:" "/var/lib/dpkg/status" >> "results.manifest"                                                                                                                       0.1s 
 => diff (sh -c apt install --no-install-recommends --allow-change-held-packages -y libxml2 tar libcurl4 libsystemd0 libc-bin libgnutls30 libtirpc3 libudev1 libx11-data libxslt1.1 perl-base libfreety  0.0s 
INFO[0017] Validated package libxml2 version 2.9.10+dfsg-6.7+deb11u4 meets requested version 2.9.10+dfsg-6.7+deb11u4 
INFO[0017] Validated package tar version 1.34+dfsg-1+deb11u1 meets requested version 1.34+dfsg-1+deb11u1 
INFO[0017] Validated package libcurl4 version 7.74.0-1.3+deb11u11 meets requested version 7.74.0-1.3+deb11u11 
INFO[0017] Validated package libsystemd0 version 247.3-7+deb11u4 meets requested version 247.3-7+deb11u2 
INFO[0017] Validated package libc-bin version 2.31-13+deb11u8 meets requested version 2.31-13+deb11u7 
ERRO[0017] downloaded package libgnutls30 version 3.7.1-5+deb11u4 lower than required 3.7.1-5+deb11u5 for update 
INFO[0017] Validated package libtirpc3 version 1.3.1-1+deb11u1 meets requested version 1.3.1-1+deb11u1 
INFO[0017] Validated package libudev1 version 247.3-7+deb11u4 meets requested version 247.3-7+deb11u2 
INFO[0017] Validated package libx11-data version 2:1.7.2-1+deb11u2 meets requested version 2:1.7.2-1+deb11u2 
INFO[0017] Validated package libxslt1.1 version 1.1.34-4+deb11u1 meets requested version 1.1.34-4+deb11u1 
INFO[0017] Validated package perl-base version 5.32.1-4+deb11u3 meets requested version 5.32.1-4+deb11u3 
INFO[0017] Validated package libfreetype6 version 2.10.4+dfsg-1+deb11u1 meets requested version 2.10.4+dfsg-1+deb11u1 
INFO[0017] Validated package libkrb5support0 version 1.18.3-6+deb11u4 meets requested version 1.18.3-6+deb11u4 
INFO[0017] Validated package libtirpc-common version 1.3.1-1+deb11u1 meets requested version 1.3.1-1+deb11u1 
INFO[0017] Validated package libwebp6 version 0.6.1-2.1+deb11u2 meets requested version 0.6.1-2.1+deb11u2 
INFO[0017] Validated package ncurses-base version 6.2+20201114-2+deb11u2 meets requested version 6.2+20201114-2+deb11u2 
INFO[0017] Validated package libk5crypto3 version 1.18.3-6+deb11u4 meets requested version 1.18.3-6+deb11u4 
INFO[0017] Validated package libpcre2-8-0 version 10.36-2+deb11u1 meets requested version 10.36-2+deb11u1 
[+] Building 16.5s (13/13) FINISHED                                                                                                                                                                           
 => resolve image config for docker.io/library/nginx:1.21.6                                                                                                                                              1.0s
 => resolve image config for docker.io/library/nginx:1.21.6                                                                                                                                              0.2s
 => CACHED docker-image://docker.io/library/debian:11-slim                                                                                                                                               0.6s
 => => resolve docker.io/library/debian:11-slim                                                                                                                                                          0.6s
 => CACHED docker-image://docker.io/library/nginx:1.21.6                                                                                                                                                 0.3s
 => => resolve docker.io/library/nginx:1.21.6                                                                                                                                                            0.3s
 => apt update                                                                                                                                                                                           2.2s
 => apt install busybox-static                                                                                                                                                                           1.1s
 => CACHED copy /bin/busybox /bin/busybox                                                                                                                                                                0.0s
 => CACHED mkdir /copa-out                                                                                                                                                                               0.0s
 => CACHED /bin/busybox sh -c ibkrb5-3 version 1.18.3-6+deb11u4 meets requested version 1.18.3-6+deb11u4 
                status="$DPKG_STATUS_IS_UNKNOWN".2+20201114-2+deb11u2 meets requested version 6.2+20201114-2+deb11u2 
                if [ -f "$DPKG_STATUS_PATH" ]; then1.dfsg-2+deb11u2 meets requested version 1:1.2.11.dfsg-2+deb11u2 
                    status="$DPKG_STATUS_IS_FILE"1.3+deb11u11 meets requested version 7.74.0-1.3+deb11u11 
                   0.0sckage gpgv version 2.2.27-2+deb11u2 meets requested version 2.2.27-2+deb11u2 
 => apt update                                                                                                                                                                                           2.3s
 => sh -c apt install --no-install-recommends --allow-change-held-packages -y libxml2 tar libcurl4 libsystemd0 libc-bin libgnutls30 libtirpc3 libudev1 libx11-data libxslt1.1 perl-base libfreetype6 li  8.8s
 => sh -c grep "^Package:\|^Version:" "/var/lib/dpkg/status" >> "results.manifest"                                                                                                                       0.1s
 => diff (sh -c apt install --no-install-recommends --allow-change-held-packages -y libxml2 tar libcurl4 libsystemd0 libc-bin libgnutls30 libtirpc3 libudev1 libx11-data libxslt1.1 perl-base libfreety  0.0s
 => => diffing     
```

### Steps To Reproduce

Copa version 0.6.0 using any of the buildkit connection methods

### Are you willing to submit PRs to contribute to this bug fix?

- [ ] Yes, I am willing to implement it.

**Comment by sozercan** [comment] 2024-02-15 03:07
duplicate of #503

**Closed by sozercan** 2024-02-15 03:07 UTC
Labels: bug
